### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by CaptainOdious** [willbob8/willsurridgetech#1]
Hi ! I've been following your tutorial trying to reproduce that 3D floor plan so far I don't have any errors and yet nothing happens in the lovelace view, it's blank... I've been trying multiple times from different web browser but I always come to the same result...

Here's my piece of code:

_Configuration.yaml:_
`lovelace:
  mode: yaml
  resources:
  - url: /hacsfiles/config-template-card/config-template-card.js
    type: module
  - url: /hacsfiles/light-entity-card/light-entity-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js 
    type: module
  - url: /hacsfiles/decluttering-card/decluttering-card.js
    type: module  `

_ui-lovelace.yaml_
`badges: []
panel: flase
  - !include ./lovelace/floorplan.yaml`

_floorplan.yaml_
`title: Floorplan
icon: mdi:floor-plan
path: floorplan
panel: true
cards:
  - type: "custom:config-template-card"
    entities:
      - light.chambre
      - light.cusine
      - light.dressing
      - light.salle_de_bain
      - light.salon
      - light.wc
    card:
      type: picture-elements
      images: local/floorplan/Appart_night.png
      style: |
          ha-card:first-child {
            background: rgba(42, 46, 48, 1)
          }
      elements:
            ### Overlay day time image when the sun is up ###
        - type: image
          action: none
          entity: sun.sun
          state_image:
            above_horizon: local/floorplan/Appart_day.png
            below_horizon: local/floorplan/Transparent.png
          style:
            height: 100%
            left: 50%
            mix-blend-mode: lighten
            opacity: "${ states[''sensor.sunlight_opacity''].state }"
            top: 50%
            width: 100%
          tap_action:
            action: none
          hold_action:
            action: none

            ### Overlay light image when the light is on ###
        - type: image
          action: none
          entity: light.chambre
          hold_action:
           action: none
          image: local/floorplan/Appart_1.png
          style:
            filter: >-
              ${ "hue-rotate(" + (states['light.chambre'].attributes.hs_color
              ? states['light.chambre'].attributes.hs_color[0] : 0) + "deg)"}
            left: 50%
            mix-blend-mode: lighten
            opacity: "${states['light.chambre'].state === 'on' ? (states['light.chambre'].attributes.brightness / 255) : '0'}"
            top: 50%
            width: 100%
            height: 100%
          tap_action:
            action: none
            
        - type: image
          action: none
          entity: light.salon
          hold_action:
           action: none
          image: local/floorplan/Appart_2.png
          style:
            filter: >-
              ${ "hue-rotate(" + (states['light.salon'].attributes.hs_color
              ? states['light.salon'].attributes.hs_color[0] : 0) + "deg)"}
            left: 50%
            mix-blend-mode: lighten
            opacity: "${states['light.salon'].state === 'on' ? (states['light.salon'].attributes.brightness / 255) : '0'}"
            top: 50%
            width: 100%
            height: 100%
          tap_action:
            action: none         
            
        - type: image
          action: none
          entity: light.dressing
          hold_action:
           action: none
          image: local/floorplan/Appart_3.png
          style:
            filter: >-
              ${ "hue-rotate(" + (states['light.dressing'].attributes.hs_color
              ? states['light.dressing'].attributes.hs_color[0] : 0) + "deg)"}
            left: 50%
            mix-blend-mode: lighten
            opacity: "${states['light.dressing'].state === 'on' ? (states['light.dressing'].attributes.brightness / 255) : '0'}"
            top: 50%
            width: 100%
            height: 100%
          tap_action:
            action: none 
            
        - type: image
          action: none
          entity: light.salle_de_bain
          hold_action:
           action: none
          image: local/floorplan/Appart_4.png
          style:
            filter: >-
              ${ "hue-rotate(" + (states['light.salle_de_bain'].attributes.hs_color
              ? states['light.salle_de_bain'].attributes.hs_color[0] : 0) + "deg)"}
            left: 50%
            mix-blend-mode: lighten
            opacity: "${states['light.salle_de_bain'].state === 'on' ? (states['light.salle_de_bain'].attributes.brightness / 255) : '0'}"
            top: 50%
            width: 100%
            height: 100%
          tap_action:
            action: none  
            
        - type: image
          action: none
          entity: light.cusine
          hold_action:
           action: none
          image: local/floorplan/Appart_6.png
          style:
            filter: >-
              ${ "hue-rotate(" + (states['light.cusine'].attributes.hs_color
              ? states['light.cusine'].attributes.hs_color[0] : 0) + "deg)"}
            left: 50%
            mix-blend-mode: lighten
            opacity: "${states['light.cusine'].state === 'on' ? (states['light.cusine'].attributes.brightness / 255) : '0'}"
            top: 50%
            width: 100%
            height: 100%
          tap_action:
            action: none   
            
        - type: image
          action: none
          entity: light.wc
          hold_action:
           action: none
          image: local/floorplan/Appart_7.png
          style:
            filter: >-
              ${ "hue-rotate(" + (states['light.wc'].attributes.hs_color
              ? states['light.wc'].attributes.hs_color[0] : 0) + "deg)"}
            left: 50%
            mix-blend-mode: lighten
            opacity: "${states['light.wc'].state === 'on' ? (states['light.wc'].attributes.brightness / 255) : '0'}"
            top: 50%
            width: 100%
            height: 100%
          tap_action:
            action: none            `

Hope you'll be able to help me. Thank you

**Comment by willbob8** [comment]
I'd love to help - could you drop me an email on will@willsurridge.co.uk and attach those 3 yaml files and I'll have a look!
