### ISSUE TITLE
Heating and popups issues

### ISSUE THREAD

**Issue by grego1981** [willbob8/willsurridgetech#2]
Hi and thank you for your work! It made my day!
Everything is working as intented apart from 2 things:

The long press or heating tap not opens the popup they should.. I have the browser_mod installed and added the browser_mod: directive to configuration.yaml but I get nothing

The second isssue is with the heating icon, I've created my own png icons but they do not seem to change in the UI... I'm sure that there is something I do not know, can you point me to the correct direction??

Thank you again for your time and effort!

**Comment by willbob8** [comment]
Hey, do you want to ping me on Facebook or email and we can continue this chat there to try and help you out :)
